name: Send Tweets from Metadata
description: Trigger the sending of tweets from a metadata object array.
author: Philipp Burckhardt <pburckhardt@outlook.com>

inputs:
  metadata:
    description: Metadata object array.
    required: true
  types: 
    description: Comma-separated list of meatadata types to generate tweets for.
    default: "bugfix, feature, release"
  rules:
    description: A file path to a JSON file containing the rules for generating tweets in the form of an object with regular expression strings and corresponding replacement strings for each type.
    default: "./rules.json"
  authors: 
    description: A file path to a JSON file containing a mapping from GitHub user names to Twitter handles.
    default: "./authors.json"
  TWITTER_CONSUMER_KEY:
    description: A valid Twitter consumer key.
    required: true
    type: string
  TWITTER_CONSUMER_SECRET:
    description: A valid Twitter consumer secret.
    required: true
    type: string
  TWITTER_ACCESS_TOKEN:
    description: A valid Twitter access token.
    required: true
    type: string
  TWITTER_ACCESS_TOKEN_SECRET:
    description: A valid Twitter access token secret.
    required: true
    type: string

runs:
  using: node12
  main: index.js

branding:
  icon: send
  color: green