# Workflow name:
name: Test GitHub Action

# Workflow triggers:
on:
  push:

# Workflow jobs:
jobs:
  test:
    # Define the type of virtual host machine on which to run the job:
    runs-on: ubuntu-latest

    # Define the sequence of job steps...
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm install
      - name: Extract metadata
        id: extract-metadata
        uses: stdlib-js/commit-metadata-action@v1
      - name: Process metadata and send tweets
        run: ./
        with:
          metadata: ${{ steps.extract-metadata.outputs.metadata }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
